language: ruby
rvm:
  - 2.3.3
before_script:
  - chmod +x ./scripts/cibuild
  - chmod +x ./scripts/pushbook.sh
script:
  - ./scripts/cibuild
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
  email: false
sudo: false
