# Programming Styles {#style}

Make pretty code.

## GitHub

All GitHub repository names should follow the `kebab-case` naming convention and be in lower case.

## R

Generally we will be sticking to [Hadley Wickham's R Style Guide](http://r-pkgs.had.co.nz/style.html) for all R code we write. Some important points to note are to try to stick to 80 characters per line (exceptions are made for `.Rmd` files or similar) and to use 2 spaces, not tabs! With regards to naming conventions, some people prefer `snake_case` where as others prefer `camelCase`; generally speaking either are fine so long as you and any collaborators are consistent with your code.

Some quick notes on what _not_ to do when programming in R:

* Don't use `attach()`
* Use `seq_along()` over `1:length(x)` when writing loops
* Use `library()`, not `require()`, [unless you need to](https://yihui.name/en/2014/07/library-vs-require/)

### Tools

The [`lintr`](https://github.com/jimhester/lintr) package is designed to help you stick to certain coding conventions. `lintr` can be executed as standalone or as part of build. It can integrated into RStudio, emacs/ess, vim etc. Using `lintr` will ensure we are all conforming to the same coding standards. Additionally, `lintr` can be [ran as part of](https://github.com/jimhester/lintr#testthat) your [`testthat` tests](#tests).

Quick formatting to code can be applied using the [`formatR`](https://yihui.name/formatr/) package. The `formatR` package was designed to reformat R code to improve readability; the main workhorse is the function `tidy_source()`. Features include:

* long lines of code and comments are reorganized into appropriately shorter ones
* spaces and indent are added where necessary
* the number of spaces to indent the code (i.e. tab width) can be specified
* an else statement in a separate line without the leading `}` will be moved one line back
* `=` as an assignment operator can be replaced with `<-`

The [`goodpractice`](https://github.com/MangoTheCat/goodpractice) is useful for giving advice about good practices when [building R packages](#package). Advice includes functions and syntax to avoid, package structure, code complexity, code formatting (using `lintr`), etc.

## Python

The below are the most immediate features that ONS code should be expected to adhere to. The recommendations
in [Effective Python](http://www.effectivepython.com) give a more in-depth idea of how to write good python code and align with our recommendations.

### Style guide

The following sections outline conditions on python code produced for sharing.

#### Spacing
Tabs are illegal. All indentation should be in spaces and each indent should be either 2 or 4 spaces.

#### Line length
No lines should exceed 80 characters. 

#### Blank lines

* __1 line__: There should be one line between blocks of code, the exceptions are where two lines are recommended.
* __2 lines__: Start and end of function definitions, import blocks, headers, and class definitions should have 2 lines clearning them.
  
*Good*

```python
import os
      
      
class Goober(object):
  """|
    docstrings are good
    docstrings are great
  """
  def __init__(self):
    pass
    
 
def main():
  pass
```

*Bad*

```python
import os
class Goober(object):
  """|
    docstrings are good
    docstrings are great
  """
  def __init__(self):
    pass
    
def main():
  pass
```

#### Data declarations
Elements must align, either in leading or following comma notation. Some examples:

```python
list_1 = [
  elem_1,
  elem_2,
  elem_3
]


list_2 = [ elem_1
         , elem_2
         , elem_3
         ] 
```

#### List comprehensions
There should be no more than 2 statements included in any list comprehension. If the comprehension is exceeding this length then break it out into a loop or multiple statements. It might make sense to you now but when somebody else comes to read it they will hate you if you don't.

#### Exceptions
Do not raise base exceptions. Create your own classes which extend them and manage your errors correctly.

#### Imports
Imports should be grouped, at the top of your file and placed in the following order.

- Standard library
- PyPI available packages
- ONS modules and those local to your project

#### Type hinting
Where possible
use [type hinting](https://docs.python.org/3/library/typing.html) as per[PEP484](https://www.python.org/dev/peps/pep-0484/). It will make your code more verbose, easier to debug and handle when others come to inherit it.
