# Code Testing {#tests}

In [functional programming](https://en.wikipedia.org/wiki/Functional_programming), code is designed to be reused again and again with different inputs, making for simpler code that is easier to understand and audit. Writing functions allows us to more easily [document](#docs) our code meaning that others can use it without too much hassle. It also means that we can build tests to ensure the code continues to work as expected when we make changes to it.

Everytime you write a new function, you should strive to write tests for that function. In fact, some people use a [test driven development](https://en.wikipedia.org/wiki/Test-driven_development) approach whereby tests are written first and a function is written second to pass those tests. In the case a bug is discovered with a function, a test should _always_ be written to ensure that bug is not reintroduced at some point in the future - you are essentially protecting yourself from future you's mistakes.

## R
There are different packages that help with writing and running tests in R such as [`RUnit`](https://cran.r-project.org/web/packages/RUnit/index.html) and [`testthat`](https://github.com/hadley/testthat). It is the latter that is generally recommended. More information about `testthat` can be found in the [R packages](http://r-pkgs.had.co.nz/tests.html) book.

## Python
* [nosetools](http://nose.readthedocs.io/en/latest/)
* [pytest](https://docs.pytest.org/en/latest/)
