# Python
The below are the most immediate features that your code should have. The recommendations in [Effective Python](http://www.effectivepython.com) give a more in-depth idea of how to write good python code and align with our recommendations.


## Style guide
The following sections outline conditions on python code produced for sharing.

#### Spacing {-}
Tabs are illegal. All indentation should be in spaces and each level of indent should be either 2 or 4 spaces, but constant throughout the project at either 2 or 4.

```{python}
import numpy as np


# Good
def main():
  """
    This is my docstring
    There are many others like it
    But this one is mine
  """
  def third_eye(n):
    return 3 * np.eye(n)
 
 
# Bad
def main():
  """
    This is my docstring
    There are many others like it
    But this one is mine
  """
  def third_eye(n):
      return 3 * np.eye(n)
```

#### Line length {-}
No lines should exceed 80 characters. If you find yourself running out of room on a line then it might be a good sign that you need to write a function. 


#### Blank lines {-}

* __1 line__: There should be one line between blocks of code, the exceptions are where two lines are recommended.
* __2 lines__: Start and end of function definitions, import blocks, headers, and class definitions should have 2 lines clearning them.


```python
# Good
import os
      
      
class Goober(object):
  """|
    docstrings are good
    docstrings are great
  """
  def __init__(self):
    pass
    
 
def main():
  pass
  
# Bad
import os
class Goober(object):
  """|
    docstrings are good
    docstrings are great
  """
  def __init__(self):
    pass
    
def main():
  pass
```

#### Data declarations {-} 
Elements must align, either in leading or following comma notation. Some examples:

```python
list_1 = [
  elem_1,
  elem_2,
  elem_3
]


list_2 = [ elem_1
         , elem_2
         , elem_3
         ] 
```

#### List comprehensions {-}
There should be no more than 2 statements included in any list comprehension. If the comprehension is exceeding this length then break it out into a loop or multiple statements. It might make sense to you now but when somebody else comes to read it they will hate you if you don't.


#### Exceptions {-}
Do not raise base exceptions. Create your own classes which extend them and manage your errors in a meaningful way.


#### Imports {-}
Imports should be grouped, at the top of your file and placed in the following order.

1. standard library imports
2. related third party imports
3. local application/library specific imports

Put a blank line between each group of imports and include a comment to show the group.  The imports in each group should be sorted alphabetically, by module name. Try to avoid `from foo import *` unless you can be absolutely certain that there are no clashes in the namespace. It may be more suitable to give your module a short alias, such as `import pandas as pd`.


#### Type hinting {-} 
Where possible use [type hinting](https://docs.python.org/3/library/typing.html) as per[PEP484](https://www.python.org/dev/peps/pep-0484/). It will make your code more verbose as well as easier to debug and handle.



## Package Management
Programs should be packages using one of two methods. First is the python solution [virtualenv](https://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/) which allows you to bundle a python executable and all of the needed packages with your program or through the use of [docker](#link-to-docker) which facilitates a wider use case and means you do not need to handle exceptions caused by windows and linux libraries and executables not being available on the system. 


## Choosing a container
What virtualenv does is simple, it copies your system python installation and supporting packages to the project root directory and then updates the python paths (when you run `activate.sh`) to point to this version. You are then free to `pip install` to your heart's content without making global changes. Whilst this allows you to localise your python packages it does not incorporate outside dependencies. If you need a running LAMP server, redis, spark or some other external tool you need to add them into your project. You essentially end up polluting your environment with project-specific dependencies. This is *not* optimal for large projects with database back ends or heavier dependencies and docker should be used. 

Docker allows you to run a virtual machine in a single thread. This allows you to pre-bundle all of the requirements you have into a single image which can be activated and allow all dependencies to be mimicked on a larger system scale. It leads to a fewer _dependency spaghetti_ issues because you can also use system software management tools such as [brew](https://brew.sh) to install things into your images.

Docker is also suitable in the use case where virtualenv is a good choice. As such docker is the recommended solution for packaging up python projects. However, it is still quite a young tool and there may be a few kinks that have you falling back on your old, faithful virtualenv. Use your judgement as to which is best in your given situation and easiest to share. Docker is preferred but is not required.


